import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import './App.css'

function App() {
  const navigate = useNavigate()
  const [text, setText] = useState('')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [fileName, setFileName] = useState(null)
  const [progress, setProgress] = useState('')

  const saveToHistory = (data, file) => {
    const history = JSON.parse(localStorage.getItem('educas_history') || '[]')
    history.unshift({ ...data, fileName: file || 'Manual Text Input', date: new Date().toLocaleDateString() })
    localStorage.setItem('educas_history', JSON.stringify(history.slice(0, 50)))
  }

  const analyzeText = async () => {
    if (!text.trim()) return alert('Please enter some text!')
    setLoading(true)
    setResult(null)
    setProgress('📤 Sending text...')
    try {
      setProgress('🤖 AI is analyzing...')
      const res = await fetch('https://educas-backend.onrender.com/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text })
      })
      setProgress('📊 Preparing results...')
      const data = await res.json()
      setResult(data)
      saveToHistory(data, null)
    } catch (e) {
      alert('Server not running!')
    }
    setLoading(false)
    setProgress('')
  }

  const handleFile = async (e) => {
    const file = e.target.files[0]
    if (!file) return
    setFileName(file.name)
    setLoading(true)
    setResult(null)
    setProgress('📤 Uploading file...')
    try {
      const formData = new FormData()
      formData.append('file', file)
      setProgress('📖 Extracting text...')
      const res = await fetch('https://educas-backend.onrender.com/upload', {
        method: 'POST',
        body: formData
      })
      setProgress('🤖 AI is analyzing...')
      const data = await res.json()
      setProgress('📊 Preparing results...')
      setResult(data)
      saveToHistory(data, file.name)
    } catch (e) {
      alert('File upload failed!')
    }
    setLoading(false)
    setProgress('')
  }

  const downloadReport = () => {
    if (!result) return
    const content = `
EDUCAS - EDUCATIONAL CONTENT ANALYSIS REPORT
=============================================

File/Text Analyzed: ${fileName || 'Manual Text Input'}
Date: ${new Date().toLocaleDateString()}

ANALYSIS RESULTS
----------------
Subject Domain:   ${result.domain}
Specific Subject: ${result.subject}
Difficulty Level: ${result.difficulty}
Suitable For:     ${result.suitableFor}

AI SUMMARY
----------
${result.summary}

RECOMMENDATIONS
---------------
${result.recommendations}

=============================================
Generated by EduCAS - Educational Content Analysis System
University of Hail - College of Computer Science and Engineering
    `.trim()
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'EduCAS_Report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="app">
      <nav className="navbar">
        <div className="nav-logo">🎓 EduCAS</div>
        <div className="nav-links">
          <button onClick={() => navigate('/')} className="nav-btn">Home</button>
          <button onClick={() => navigate('/analyze')} className="nav-btn active">Analyze</button>
          <button onClick={() => navigate('/history')} className="nav-btn">History</button>
          <button onClick={() => navigate('/stats')} className="nav-btn">Statistics</button>
          <button onClick={() => navigate('/about')} className="nav-btn">About</button>
          <button onClick={() => navigate('/login')} className="nav-btn login-btn">Login</button>
        </div>
      </nav>

      <div className="app-inner">
        <header>
          <div className="header-logo">🎓</div>
          <h1>EduCAS</h1>
          <p>Educational Content Analysis System</p>
          <p className="header-sub">University of Hail · College of Computer Science</p>
        </header>

        <main>
          <div className="input-section">
            <h2>📄 Upload a File</h2>
            <label className="upload-box">
              <input type="file" accept=".pdf,.docx,.txt" onChange={handleFile} style={{ display: 'none' }} />
              <div className="upload-content">
                <span className="upload-icon">📁</span>
                <p>{fileName ? fileName : 'Click to upload PDF, DOCX, or TXT'}</p>
                <small>Max 5MB</small>
              </div>
            </label>
            <div className="divider">— OR —</div>
            <h2>✏️ Paste Text</h2>
            <textarea
              rows={8}
              placeholder="Paste a paragraph from a textbook, article, or document..."
              value={text}
              onChange={e => setText(e.target.value)}
            />
            <button onClick={analyzeText} disabled={loading}>
              {loading ? '⏳ Analyzing...' : '🔍 Analyze Content'}
            </button>
          </div>

          {loading && (
            <div className="progress-box">
              <div className="spinner"></div>
              <p>{progress}</p>
              <div className="progress-bar"><div className="progress-fill"></div></div>
            </div>
          )}

          {result && !loading && (
            <div className="results">
              <div className="results-header">
                <h2>📊 Analysis Results</h2>
                <button className="download-btn" onClick={downloadReport}>⬇️ Download Report</button>
              </div>
              <div className="cards">
                <div className="card"><h3>📚 Subject Domain</h3><p className="big">{result.domain}</p></div>
                <div className="card"><h3>🎯 Specific Subject</h3><p className="big">{result.subject}</p></div>
                <div className="card"><h3>📖 Difficulty Level</h3><p className="big">{result.difficulty}</p></div>
                <div className="card"><h3>✅ Suitable For</h3><p className="big">{result.suitableFor}</p></div>
              </div>
              <div className="summary-box"><h3>💡 AI Summary</h3><p>{result.summary}</p></div>
              <div className="summary-box"><h3>📝 Recommendations</h3><p>{result.recommendations}</p></div>
            </div>
          )}
        </main>

        <footer>
          <p>🎓 EduCAS · University of Hail · Department of Software Engineering</p>
        </footer>
      </div>
    </div>
  )
}

export default App
